[project]
name = "pr-reviewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "mcp[cli]>=1.4.0",
    "notion-client>=2.3.0",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
]
